---
# vim
- name: init neobundle
  git: repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim

# current repos
- name: check current git repos
  stat: path={{ ansible_env.PWD }}/.git
  register: resgit
- shell: |
    cd {{ ansible_env.PWD }}
    git init
    git remote add origin https://github.com/yakisuzu/provisioning-ansible.git
    git fetch origin
    git reset origin/master
    git config --local user.name yakisuzu
    git config --local user.email yakisuzu@gmail.com
  when: not resgit.stat.exists

