---
# vim
- name: init neobundle
  git: repo=git@github.com:Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim
- name: init vimrc
  git: repo=git@github.com:yakisuzu/dotfiles dest=~/dotfiles
  notify: mklink vimrc

# current repos
- name: check current git repos
  stat: path={{ ansible_env.PWD }}/.git
  register: resgit
- shell: |
    cd {{ ansible_env.PWD }}
    git init
    git remote add origin git@github.com:yakisuzu/provisioning-ansible.git
    git fetch origin
    git reset origin/master
  when: not resgit.stat.exists
