---
- name: apt update
  apt: update_cache=yes
  become: yes

# before setting
- name: git install
  apt: name=git state=latest

- include: dotfiles.yml

- name: install package for apt
  apt: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
  with_items: apt_packages
  when: apt_packages

- name: create nodejs symlink
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
