---
- name: apt update
  apt: update_cache=yes
  sudo: yes

- name: install package for apt
  apt: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
  with_items: apt_packages
  when: apt_packages

- name: create nodejs symlink
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
