---
- name: apt update
  apt: update_cache=yes

- name: install package for apt
  apt: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
  with_items: apt_packages
  when: apt_packages
