---
- include_vars: "{{ ansible_os_family }}.yml"

- include: before.yml

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: after.yml

