---
- include_vars: "{{ ansible_os_family }}.yml"

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- stat: path={{ ansible_env.PWD }}/.git
  register: resgit
- shell: |
    cd {{ ansible_env.PWD }};
    git init;
    git remote add origin git@github.com:yakisuzu/provisioning-ansible.git;
    git fetch origin;
    git reset origin/master;
  when: not resgit.stat.exists
