---
- name: yum update
  yum: update_cache=yes
  #become: yes

# before setting
- name: git install
  yum: name=git state=latest

- include: dotfiles.yml

- name: install package for yum
  yum: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
  with_items: yum_packages
  when: yum_packages
